### ISSUE TITLE
請在 HW1 資料夾裡新增 requirements.txt

### ISSUE THREAD

**Issue by D0683497** [cjchengtw/HackerSir-Cadre-Training#2]
+ 創建 Python 虛擬環境
    + [參考文件](https://docs.python.org/3/library/venv.html?highlight=venv#module-venv)
+ 安裝必要插件
+ 匯出 requirements.txt
    + `pip freeze > requirements.txt`

**Comment by cjchengtw** [comment]
我現在使用 pipenv 一個整合pip和virtual env 的套件，所以沒有上傳的是 Pipfile 而不是 requirements.txt
筆記：https://hackmd.io/Tnwv-p_sR0qSQ-OUe6AZWw#（持續更新中）
